### PR TITLE
sima0_13_003: Fix model crash in MPAS dynamical core and implement assorted code cleanup

### LINKED ISSUE #484: MPAS QPC4 simulation fails with latest GNU + DEBUG
### What happened?

On Derecho if you try to run the QPC4 compset with MPAS (e.g. `mpasa120_mpasa120`) with the head of CAM-SIMA with the gnu compiler (gnu v14.3.0), and with `DEBUG` set to `TRUE` in `env_build.xml` (which turns on the compiler debug flags), the model will crash with the following error:

```
 SIGSEGV: Segmentation fault - invalid memory reference.
```

The traceback points to the following file/line:

```
#1  0xde207f in __dyn_mpas_subdriver_MOD_dyn_mpas_map_constituent_index at /glade/derecho/scratch/nusbaume/model_runs/SIMA_MPAS_QPC4_test/bld/atm/obj/mpas/driver/dyn_mpas_subdriver.F90:3342
```

### What are the steps to reproduce the bug?

With the head of the development branch of ESCOMP/CAM-SIMA, do the following:

```
create_newcase --case <case_dir> --res mpasa120_mpasa120 --mach derecho --compset QPC4 --compiler gnu --run-unsupported
cd <case_dir>
./xmlchange DEBUG=TRUE
./xmlchange --append CAM_CONF_OPTS="--analytic-ic" 
cp /glade/derecho/scratch/nusbaume/model_runs/SIMA_NCAR_MPAS_QPC4_test/user_nl_cam ./user_nl_cam
./case.build
./case.submit
```

The model should start running and then crash with the error described above.

### What CAM-SIMA hash were you using?

5b83a2d

### What machine were you running CAM-SIMA on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

GNU

### Path to a case directory, if applicable

/glade/derecho/scratch/nusbaume/model_runs/SIMA_NCAR_MPAS_QPC4_test

### Will you be addressing this bug yourself?

Any Software Engineer can do this

### Extra info

This configuration does run when debug flags are turned off (e.g. `DEBUG=FALSE` in `env_build.xml`), which is what the current regression test runs (hence why the bug wasn't caught).

### PR DESCRIPTION
**Pull request by kuanchihwang**
### Tag name (required for release branches):

sima0_13_003 due to newly-added tests, otherwise bit-for-bit.

### Originator(s):

kuanchihwang

### Descriptions (include the issue title, and the keyword ['closes', 'fixes', 'resolves'] followed by the issue number):

This PR fixes a model crash in MPAS dynamical core, which is caused by a regression in recent versions of GNU Fortran compiler. When CAM-SIMA is configured with MPAS dynamical core, and is built with GNU Fortran compiler version 14 in debug mode, running the model will lead to a segmentation fault. However, the crash mysteriously disappears when the model is built in optimized mode. Older GNU Fortran compiler version 12 does not exhibit this behavior, neither does Intel Fortran compiler.

Closes #484

Additionally, this PR also brings the following:

1. Update Python script for generating MPAS namelist definition file
2. Reduce API surface area by making `dyn_inquire_mesh_dimensions` private
3. Add lookup table for mapping indexes from advected to all constituents and refactor the rest of code to use it
4. Fix incorrect constituent indexing inside `set_physics_state_external` during dynamics-physics coupling

The rationale behind each change is described in the commit messages.

### Describe any changes made to the build system:

None

### Describe any changes made to the namelist:

None

### List any changes to the defaults for the input datasets (e.g., boundary datasets):

None

### List all files eliminated and why:

None

### List all files added and what they do:

None

### List all existing files that have been modified, and describe the changes:

```
M       src/dynamics/mpas/assets/generate_namelist_definition.py
  * Update Python script for generating MPAS namelist definition file
M       src/dynamics/mpas/dyn_comp.F90
  * Add lookup table for mapping indexes from advected to all constituents
M       src/dynamics/mpas/dyn_comp_impl.F90
  * Add lookup table for mapping indexes from advected to all constituents
  * Fix MPAS dycore crash due to regression in recent GNU Fortran compiler
M       src/dynamics/mpas/dyn_coupling_impl.F90
  * Fix indentation
  * Add lookup table for mapping indexes from advected to all constituents
  * Fix MPAS dycore crash due to regression in recent GNU Fortran compiler
  * Fix incorrect constituent indexing
M       src/dynamics/mpas/dyn_grid.F90
  * Make `dyn_inquire_mesh_dimensions` private
M       src/dynamics/mpas/dyn_grid_impl.F90
  * Make `dyn_inquire_mesh_dimensions` private
M       src/dynamics/mpas/dyn_procedures.F90
  * Fix MPAS dycore crash due to regression in recent GNU Fortran compiler
M       src/dynamics/mpas/tests/unit/test_dyn_procedures.pf
  * Fix MPAS dycore crash due to regression in recent GNU Fortran compiler
```

### Regression tests:

```
SMS_Ln9.ne3pg3_ne3pg3_mg37.FADIAB.derecho_gnu.cam-outfrq_se_cslam (Overall: FAIL)
SMS_Ln9.ne3pg3_ne3pg3_mg37.FKESSLER.derecho_intel.cam-outfrq_se_cslam_multitape (Overall: NLFAIL)
```

Known failing tests.

```
SMS_D_Ln9.mpasa120_mpasa120.QPC4.derecho_gnu.cam-outfrq_analy_ic_cam4 (Overall: DIFF)
SMS_D_Ln9.mpasa120_mpasa120.QPC4.derecho_intel.cam-outfrq_analy_ic_cam4 (Overall: DIFF)
```

Newly-added tests.

### CODE REVIEW

File: src/dynamics/mpas/dyn_comp_impl.F90 [hunk 1]
```diff
@@ -658,29 +703,20 @@ subroutine set_mpas_state_scalars()
...
-                if (const_is_advected(i)) then
-                    constituent_index(j) = i
-                    if (j == num_advected) then
-                        exit !Break out of loop if no more advected constituents
-                    else
-                        j = j + 1
-                    end if
-                end if
-            end do
+            constituent_index(:) = [(advected_constituent_index(i), i = 1, num_advected)]
```
Comment (nusbaume) [inline src/dynamics/mpas/dyn_comp_impl.F90]: Do we need `constituent_index` anymore?  It looks like we could just use `advected_constituent_index` as-is in this subroutine instead.

**Review by nusbaume — CHANGES_REQUESTED** [review]
Thanks for the bug fix and cleanup @kuanchihwang!  To help us catch these potential issues in the future, I was wondering if we could add another set of MPAS+CAM4 regression tests, but this time with debug flags enabled?  This should be doable by just adding the following lines to  `CAM-SIMA/cime_config/testdefs/testlist_cam.xml`, ideally at the end of the `CAM4 physics tests` section:

```
<test compset="QPC4" grid="mpasa120_mpasa120" name="SMS_D_Ln9" testmods="cam/outfrq_analy_ic_cam4">
    <machines>
      <machine name="derecho" compiler="intel" category="aux_sima"/>
      <machine name="derecho" compiler="gnu" category="aux_sima"/>
    </machines>
    <options>
      <option name="wallclock">00:20:00</option>
      <option name="comment">Aquaplanet CAM4 test with MPAS dycore at 120 km resolution  with compiler debug flags enabled</option>
    </options>
 </test>
```

I also had one code-related question, but otherwise everything else looked good to me.  Thanks again!

File: src/dynamics/mpas/dyn_comp_impl.F90 (hunk 1 above)
Comment (kuanchihwang) [reply src/dynamics/mpas/dyn_comp_impl.F90]: Thanks for spotting this! I removed the array in https://github.com/ESCOMP/CAM-SIMA/pull/486/commits/276177d5994d528b8360b60a0af7bd9b8488eaf6.

Also, I added a new CIME test in https://github.com/ESCOMP/CAM-SIMA/pull/486/commits/bc4bef94e9169786026cb4076a279bd7698366b7.

**Review by nusbaume — APPROVED** [review]
Everything looks great to me now.  Thanks again @kuanchihwang!

**Review by jimmielin — APPROVED** [review]
Thanks @kuanchihwang!
