### PR TITLE
sima0_12_000: Implement tracer_data in CAM-SIMA; registry entries for prescribed ozone/BAM; NaN check in physics data check

### LINKED ISSUE #432: CCPPize/move tracer_data to CAM-SIMA
This task is make `tracer_data`, a module used to read and interpolate offline (file-based) tracer data (sources and mixing ratios) used by chemistry and aerosols, a part of CAM-SIMA.

This module has to reside in the host model because it has decomposed I/O for unstructured grids.

Rough subtasks

- [x] Dechunkize
- [x] Remove dependency on `pbuf` and change to storing data array left and right brackets within the data containers
- [ ] Abstract decomposed I/O on `physgrid` to separate host-model dependent module: `tracer_data_physgrid_io.F90`
- [ ] Change to use CCPP I/O reader
- [x] Remove other CAM dependencies
- [x] Move `tracer_data.F90` to CAM-SIMA
- [ ] Change CAM to use the generic `tracer_data.F90` from a CAM-SIMA sparse checkout
- [x] Any necessary refactoring
- [ ] Make working in current CAM
- [x] CCPPize a sample scheme (currently slated to be `prescribed_ozone.F90`) for test in SIMA

This module has to somehow receive model lat/lon information (which is dechunkized) for spatial interpolation. 

~~If this becomes an atmos_phys utility module, a "helper" CCPP scheme will be needed to update needed model information and advance the tracer data through timestepping (maybe a `timestep_init` only phase).~~

The timestepping appears to be managed by the host model code by calling `trcdata_advance`; this needs to be coordinated with dechunkizing

### LINKED ISSUE #440: NaNs in model state are not detected by physics data differences check
### What happened?

Any NaN values in the model state go unreported by physics check against snapshot because the check is currently written as
```fortran
if (diff > min_difference) then
   diff_count = diff_count + 1
end if
```
is always `.false.` and thus does not increment the count if `diff` is a NaN (NaN comparisons will always be false)

### What are the steps to reproduce the bug?

Put in a NaN in any checked physics field

### What CAM-SIMA hash were you using?

04a0b5aa68fdfac9152fcd785ccba9894c0bf2e1

### What machine were you running CAM-SIMA on?

CISL machine (e.g. cheyenne)

### What compiler were you using?

GNU

### Path to a case directory, if applicable

_No response_

### Will you be addressing this bug yourself?

Yes

### Extra info

Will address with tracer_data PR

### PR DESCRIPTION
**Pull request by jimmielin**
Tag name (required for release branches): sima0_12_000
Originator(s): @jimmielin 

Description (include the issue title, and the keyword ['closes', 'fixes', 'resolves'] followed by the issue number):
- Port tracer_data, a generic reader for chemistry and aerosol data, from CAM to CAM-SIMA. The module is as close to the original tracer_data as possible, only removing CAM-specific features (i.e., chunking and physics buffer), FV dycore polar averaging, structured dycore latitude weighting, and a rmv_file flag that deletes files after being read -- closes #432.
- Moves conservative regridding utility `src/utils/horizontal_interpolate.F90` to CAM-SIMA (intended to be included in a sparse checkout from CAM in the future) -- currently only used for aircraft inputs, but could be used for all regridded data read from tracer_data in the future.
- Add string utilities `increment_string`, `last_non_digit`, and `get_last_significant_char` in support of tracer_data.
- Add registry entries for prescribed bulk (BAM) aerosol and prescribed ozone for radiation.
- Add tracer_data chemistry and aerosols (BAM) input regression test (Derecho GNU).
- Add a check for NaN values in physics check data -- closes #440.
If any NaN values are detected in the model state, the difference count is incremented and the maximum difference will be denoted as NaN.
The number of NaNs will be reported in the output. e.g.,
```
 ********** Physics Check Data Results **********

 TIMESTEP:            1

 Variable                                          # Diffs  Max Diff   Max Diff loc (rank, col, lev)
 --------                                          -------  --------   -----------------------------
 ocar1                                                  48       NaN   (0,1,25)
 (!) 48 NaN values in variable!
 bcar1                                                  48       NaN   (0,1,25)
 (!) 48 NaN values in variable!
 sslt1                                                  48       NaN   (0,1,25)
```

Describe any changes made to build system: N/A

Describe any changes made to the namelist: N/A

List any changes to the defaults for the input datasets (e.g. boundary datasets): N/A

List all files eliminated and why: N/A

List all files added and what they do:
```
A       src/utils/tracer_data.F90
  - new tracer_data utility in CAM-SIMA ported from CAM (will not be moved from CAM)

A       src/utils/horizontal_interpolate.F90
  - move horizontal_interpolate conservative regridder for chemistry data from CAM.

A       cime_config/testdefs/testmods_dirs/cam/outfrq_trcdata_bam_derecho/shell_commands
A       cime_config/testdefs/testmods_dirs/cam/outfrq_trcdata_bam_derecho/user_nl_cam
  - new tracer_data chemistry and aerosols input data regression test.
```

List all existing files that have been modified, and describe the changes: 
(Helpful git command: `git diff --name-status development...<your_branch_name>`)
```
M       cime_config/testdefs/testlist_cam.xml
  - new tracer_data chemistry and aerosols input data regression test.

M       src/data/registry.xml
  - add prescribed ozone for radiation.
  - add prescribed BAM aerosol fields for radiation (used for input check).

M       src/physics/utils/physics_data.F90
  - check for NaNs in physics data check.

M       src/physics/utils/physics_grid.F90
  - make public the `dycore_unstructured` logical for tracer_data.

M       src/utils/string_utils.F90
  - new string utilities `increment_string`, `last_non_digit`, and `get_last_significant_char` in support of tracer_data.
```

If there are new failures (compared to the `test/existing-test-failures.txt` file),
have them OK'd by the gatekeeper, note them here, and add them to the file.
If there are baseline differences, include the test and the reason for the
diff. What is the nature of the change? Roundoff?

derecho/intel/aux_sima:
```
  SMS_Ln9.ne3pg3_ne3pg3_mg37.FKESSLER.derecho_intel.cam-outfrq_se_cslam_multitape (Overall: NLFAIL) details:
    FAIL SMS_Ln9.ne3pg3_ne3pg3_mg37.FKESSLER.derecho_intel.cam-outfrq_se_cslam_multitape NLCOMP
  - known NLFAIL due to cime validation error on multiple history tapes (#430)
```

derecho/gnu/aux_sima:
```
  SMS_Ln2.ne3pg3_ne3pg3_mg37.FPHYStest.derecho_gnu.cam-outfrq_trcdata_bam_derecho (Overall: DIFF) details:
    FAIL SMS_Ln2.ne3pg3_ne3pg3_mg37.FPHYStest.derecho_gnu.cam-outfrq_trcdata_bam_derecho NLCOMP
    FAIL SMS_Ln2.ne3pg3_ne3pg3_mg37.FPHYStest.derecho_gnu.cam-outfrq_trcdata_bam_derecho BASELINE /glade/campaign/cesm/community/amwg/sima_baselines/latest_gnu: ERROR BFAIL baseline directory '/glade/campaign/cesm/community/amwg/sima_baselines/latest_gnu/SMS_Ln2.ne3pg3_ne3pg3_mg37.FPHYStest.derecho_gnu.cam-outfrq_trcdata_bam_derecho' does not exist
  - new baseline for new trcdata_bam test.

  SMS_Ln9.ne3pg3_ne3pg3_mg37.FADIAB.derecho_gnu.cam-outfrq_se_cslam (Overall: FAIL) details:
    FAIL SMS_Ln9.ne3pg3_ne3pg3_mg37.FADIAB.derecho_gnu.cam-outfrq_se_cslam RUN time=9
  - known FAIL on shr_reprosum_calc call from src/dynamics/se/dycore/global_norms_mod.F90

```

derecho/nvhpc/aux_sima: All PASS

If this changes climate describe any run(s) done to evaluate the new
climate in enough detail that it(they) could be reproduced:

CAM-SIMA date used for the baseline comparison tests if different than latest:

### CODE REVIEW

File: src/utils/horizontal_interpolate.F90 [hunk 1]
```diff
@@ -0,0 +1,360 @@
...
+
+    normalize_lon_right = right
+
+    do while (normalize_lon_right <= left)
+      normalize_lon_right = normalize_lon_right + 360.0_r8
+    end do
+    do while (normalize_lon_right - 360.0_r8 > left)
+      normalize_lon_right = normalize_lon_right - 360.0_r8
+    end do
+    return
```
Comment (nusbaume) [inline src/utils/horizontal_interpolate.F90]: You can remove the `return` lines at the end of functions/subroutines here and below.

File: src/utils/horizontal_interpolate.F90 [hunk 2]
```diff
@@ -0,0 +1,360 @@
...
+    call check_invariant(((-2000.0_r8 < sim_left) .and. (sim_left < 2000.0_r8)), "sim_left is out of range")
+    call check_invariant(((-2000.0_r8 < sim_right) .and. (sim_right < 2000.0_r8)), "sim_right is out of range")
+
+    overlap_len = calculate_lon_overlap(input_left, input_right, sim_left, sim_right)
+
+    if (overlap_len == 0) then
+      ! No overlap; weight is zero
+      lon_weight = 0
+
+    elseif (use_flight_distance) then
```
Comment (nusbaume) [inline src/utils/horizontal_interpolate.F90]: Add space here to match formatting in the rest of the file?


```suggestion
    else if (use_flight_distance) then
```

File: src/utils/tracer_data.F90 [hunk 3]
```diff
@@ -0,0 +1,2751 @@
...
+    if (file%top_bndry .and. file%top_layer) then
+      call endrun('trcdata_init: Cannot set both file%top_bndry and file%top_layer to TRUE.')
+    end if
+
+    if (masterproc) then
+      write (iulog, *) 'trcdata_init: data type: '//trim(data_type)//' file: '//trim(filename)
+    end if
+
+    ! if there is no list of files (len_trim(file%filenames_list)<1) then
+    !  -> set curr_filename from namelist rather from restart data
```
Comment (nusbaume) [inline src/utils/tracer_data.F90]: grammar fix:


```suggestion
    !  -> set curr_filename from namelist rather than from restart data
```

File: src/utils/tracer_data.F90 [hunk 4]
```diff
@@ -0,0 +1,2751 @@
...
+  public :: advance_trcdata
+  public :: get_fld_data
+  public :: get_fld_ndx
+  public :: write_trc_restart
+  public :: read_trc_restart
+  public :: init_trc_restart
+  public :: incr_filename
+
+  type input3d
+    real(r8), dimension(:, :), pointer :: data => null() ! ncol, lev
```
Comment (nusbaume) [inline src/utils/tracer_data.F90]: I am wondering if all of the `pointer` variables in these various module-level DDT declarations can in-fact be `allocatable` instead.  This could not only improve performance, but also help reduce the risk of memory leaks.  Maybe worth seeing what pointers at this scope can be set to `allocatable` instead and still behave correctly?

File: src/utils/tracer_data.F90 [hunk 5]
```diff
@@ -0,0 +1,2751 @@
...
+
+      open (unit=unitnumber, file=filepath, iostat=ios, status="OLD")
+      if (ios /= 0) then
+        call endrun('not able to open file: '//trim(filepath))
+      end if
+
+      !-------------------------------------------------------------------
+      !  ...  read file names
+      !-------------------------------------------------------------------
+      read (unit=unitnumber, fmt='(A)', iostat=ios) line
```
Comment (nusbaume) [inline src/utils/tracer_data.F90]: I would add an `iomsg` output here to include in the `endrun` call below:


```suggestion
      read (unit=unitnumber, fmt='(A)', iostat=ios, iomsg=errmsg) line
```

This same request holds for the other `read` statements below as well.

File: src/utils/tracer_data.F90 [hunk 6]
```diff
@@ -0,0 +1,2751 @@
...
+
+      if (present(data)) then
+        if (associated(data)) then
+          deallocate (data, stat=ierr)
+          if (ierr /= 0) then
+            write (iulog, *) 'get_dimension: data deallocation error = ', ierr
+            call endrun('get_dimension: failed to deallocate data array')
+          end if
+        end if
+        allocate (data(dsize), stat=ierr)
```
Comment (nusbaume) [inline src/utils/tracer_data.F90]: Add `errmsg` here, and in the `endrun` call below (or replace with `check_allocate`)?

File: src/utils/tracer_data.F90 [hunk 7]
```diff
@@ -0,0 +1,2751 @@
...
+          trg(n, i) = trg(n, i)/(trg_x(n, i + 1) - trg_x(n, i))
+        end do
+      end if
+
+    end do
+
+  end subroutine vert_interp_mixrat
+
+  ! Interpolate data from current time-interpolated values to model levels
+  subroutine vert_interp(ncol, levsiz, pin, pmid, datain, dataout)
```
Comment (nusbaume) [inline src/utils/tracer_data.F90]: I believe this subroutine can be labeled `pure` (or even turned into a function as it only has one output).

File: src/utils/tracer_data.F90 [hunk 8]
```diff
@@ -0,0 +1,2751 @@
...
+          dataout(i, k) = (datain(i, kupper(i))*dpl + &
+                           datain(i, kupper(i) + 1)*dpu)/(dpl + dpu)
+        end if
+      end do
+    end do
+
+  end subroutine vert_interp
+
+  ! Interpolate data from current time-interpolated values to top interface pressure
+  subroutine vert_interp_ub(ncol, nlevs, plevs, datain, dataout)
```
Comment (nusbaume) [inline src/utils/tracer_data.F90]: I believe this subroutine can be labeled `pure` (or even turned into a function as it only has one output).

File: src/utils/tracer_data.F90 [hunk 9]
```diff
@@ -0,0 +1,2751 @@
...
+        index = i - 1
+        return
+      end if
+    end do
+
+  end subroutine findplb
+
+  ! rebin src (source) to trg (target).
+  ! originally from mo_util
+  pure subroutine rebin(nsrc, ntrg, src_x, trg_x, src, trg)
```
Comment (nusbaume) [inline src/utils/tracer_data.F90]: Can we get rid of this subroutine entirely, and instead just use the one from `ccpp_tuvx_utils`?

File: src/physics/utils/physics_data.F90 [hunk 10]
```diff
@@ -585,26 +589,49 @@ subroutine check_field_2d(file, var_names, timestep, current_value,        &
...
+               ! First, check if there are NaNs anywhere in the state
+               if (shr_infnan_isnan(current_value(col))) then
+                  nan_count = nan_count + 1
+                  has_nan = .true.
+
+                  ! Set max diff to NaN (if not already) to signal NaN was found
+                  if (.not. shr_infnan_isnan(max_diff(1))) then
+                     max_diff(1) = current_value(col) - buffer(col) ! = nan
+                     max_diff_col = col
+                  end if
```
[the remark this answers is not in the document]
Comment (jimmielin) [reply src/physics/utils/physics_data.F90]: Thanks, updated!

File: src/utils/tracer_data.F90 [hunk 11]
```diff
@@ -0,0 +1,2751 @@
...
+    character(len=shr_kind_cl)  :: next_filename = ' '
+    type(file_desc_t) :: curr_fileid
+    type(file_desc_t) :: next_fileid
+
+    type(var_desc_t), pointer :: currfnameid => null() ! pio restart file var id
+    type(var_desc_t), pointer :: nextfnameid => null() ! pio restart file var id
+
+    character(len=shr_kind_cl) :: filenames_list = ''
+    real(r8) :: datatimem = -1.e36_r8     ! time of prv. values read in
+    real(r8) :: datatimep = -1.e36_r8     ! time of nxt. values read in
```
[the remark this answers is not in the document]
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Thanks, updated to use `-unset_real`

File: src/utils/tracer_data.F90 [hunk 12]
```diff
@@ -0,0 +1,2751 @@
...
+                 pio_inq_dimid, pio_inq_varid, &
+                 pio_def_dim, pio_def_var, &
+                 pio_put_att, pio_put_var, &
+                 pio_get_var, pio_get_att, pio_nowrite, pio_inq_dimlen, &
+                 pio_inq_vardimid, pio_inq_dimlen, pio_closefile, &
+                 pio_inquire_variable
+
+  implicit none
+  private
+  save
```
[the remark this answers is not in the document]
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Thanks, removed!

File: src/utils/tracer_data.F90 [hunk 13]
```diff
@@ -0,0 +1,2751 @@
...
+      if (masterproc) write(iulog, *) 'incr_flnm: old filename = ', trim(filename)
+      if (masterproc) write(iulog, *) 'incr_flnm: open filenames_list : ', trim(filenames_list)
+      unitnumber = shr_file_getUnit()
+      if (present(datapath)) then
+        filepath = trim(datapath)//'/'//trim(filenames_list)
+      else
+        filepath = trim(filenames_list)
+      end if
+
+      open (unit=unitnumber, file=filepath, iostat=ios, status="OLD")
```
[the remark this answers is not in the document]
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Thanks, I removed the
```fortran
unitnumber = shr_file_getUnit()
```
to replace with `newunit=` in the `open` call. Appended `errmsg` to the `endrun`

File: src/utils/tracer_data.F90 (hunk 5 above)
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Thanks, added errmsg and appended to endrun message

File: src/utils/tracer_data.F90 [hunk 14]
```diff
@@ -0,0 +1,2751 @@
...
+    character(len=512) :: errmsg
+    character(len=*), parameter :: subname = "read_2d_trc"
+
+    nullify (wrk2d_in)
+    allocate (wrk2d(cnt(1), cnt(2)), stat=ierr, errmsg=errmsg)
+    call check_allocate(ierr, subname, 'wrk2d(cnt(1), cnt(2))', &
+                        file=__FILE__, line=__LINE__, errmsg=errmsg)
+
+    if (order(1) /= 1 .or. order(2) /= 2 .or. cnt(1) /= file%nlon .or. cnt(2) /= file%nlat) then
+      allocate (wrk2d_in(file%nlon, file%nlat), stat=ierr)
```
[the remark this answers is not in the document]
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Oops, missed it! Really sharp eyes!

File: src/utils/tracer_data.F90 [hunk 15]
```diff
@@ -0,0 +1,2751 @@
...
+      if (slen < SHR_KIND_CL) tr_file%next_filename(slen + 1:) = ' '
+    end if
+    call PIO_SetErrorHandling(piofile, err_handling)
+
+  end subroutine read_trc_restart
+
+  !------------------------------------------------------------------------------
+  ! Various utility subroutines below:
+  !------------------------------------------------------------------------------
+  subroutine interpz_conserve(nsrc, ntrg, src_x, trg_x, src, trg)
```
[the remark this answers is not in the document]
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Thanks, marked as `pure`

I kept it as a `subroutine`, though, here and below. I think it might be good to share this with CAM eventually so I didn't want to change the subroutine signatures too much to facilitate that.

File: src/utils/tracer_data.F90 (hunk 7 above)
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Thanks, marked as `pure`!

File: src/utils/tracer_data.F90 [hunk 16]
```diff
@@ -0,0 +1,2751 @@
...
+    end if
+
+    do i = 1, ncol
+      dataout(i) = datain(i, kl) + delp*(datain(i, ku) - datain(i, kl))
+    end do
+
+  end subroutine vert_interp_ub
+
+  ! Interpolate data from current time-interpolated values to press
+  subroutine vert_interp_ub_var(ncol, nlevs, plevs, press, datain, dataout)
```
[the remark this answers is not in the document]
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Thanks, marked as `pure`!

File: src/utils/tracer_data.F90 (hunk 8 above)
Comment (jimmielin) [reply src/utils/tracer_data.F90]: Thanks, marked as `pure`!

**Review by nusbaume — APPROVED** [review]
Everything looks good to me now, thanks @jimmielin!  I think the only outstanding request is to remove the copy of `rebin`, but I don't think that requires an extra re-review from me.  Thanks again!

File: src/core_utils/string_core_utils.F90 [hunk 17]
```diff
@@ -294,4 +297,112 @@ pure subroutine tokenize_into_tokens_separator(string, set, tokens, separator)
         end if
     end subroutine tokenize_into_tokens_separator
 
+    ! Increment a string whose ending characters are digits.
```
[the remark this answers is not in the document]
Comment (fvitt) [reply src/core_utils/string_core_utils.F90]: It would be nice to clean this up.  If you want to do it an a future PR, that's fine with me.
